### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by gld1982ltd** [vera-desktop/vera-plugin-openbox#2]
```shell
[Entering directory src/vera-color]
PYC openbox-vera-color.py
Failed to build file 'openbox-vera-color.pyc'
[Build failed]
```

**Comment by g7** [comment]
Hello,

the snapshot of bake we're using (0.1.33) has a buggy support for python and thus the Recipe for openbox-vera-color is pretty hacky.
Once I upgrade to the latest bake I'll try.


Eugenio

**Comment by g7** [comment]
I cant reproduce your bug, even with the latest version of bake.

Could you please re-try compiling with `bake --verbose`?


Eugenio

**Comment by gld1982ltd** [comment]
```shell
[Entering directory src/vera-color]
echo '#!/bin/sh' > vera-color
echo 'exec python openbox-vera-color.py' >> vera-color
chmod +x vera-color
python -m py_compile openbox-vera-color.py
Failed to build file 'openbox-vera-color.pyc'
[Build failed]
```

**Comment by g7** [comment]
It seems that bake has some issues in obtaining the correct Python version. I'm creating a patch that should resolve the issue.


Eugenio

**Comment by g7** [comment]
This has been resolved. You must patch bake using [this patch](https://github.com/semplice/bake/compare/python_version.patch) (in our bake repository is in the python_version branch).


Eugenio

**Comment by gld1982ltd** [comment]
I have tried with both merging the required branches and i have tried by patching the official bake package. I am still getting an error. 

```shell
Unable to compile library openbox:
 - Unable to find Vala package libconfig
[Build failed]
```

**Comment by g7** [comment]
The libconfig vapi file is available at: https://github.com/semplice/libconfig-vapi


Eugenio
